### PR TITLE
Various frontend bug fixes

### LINKED ISSUE #5: Rework mod_view_page handlebar to not need data_string
Find a way to make mod_view_page not need data_string, as it's just duplicating data for no reason whatsoever.
Make it so only the optional values are present, or obtain the values via [`XMLHttpRequest`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest)

Another idea by @Razboy20 was to use the Fetch API instead of XHR; your choice.
Imo XHR should be chosen over Fetch to make sure cross-origin is not used, which can cause issues with people using extensions such as uMatrix or other anti tracker stuff such as firefox's builtin tracker protection. (This is an issue mainly for requests that send data)

### LINKED ISSUE #12: Make search results open the correct version and/or verification of the mod.
Currently it just goes to the latest version, add the version and verification Query parameters to it.

### LINKED ISSUE #18: Clear current results from search when parameters are changed
Currently, clicking search doesn't clear the current items on the search, which means there's no way to know if some search of combination of options doesn't have any results.

### PR DESCRIPTION
**Pull request by Conqu3red**
- Search reloads properly ( fixed #18 )
- Removed categories search option
- Search results redirect to correct mod version ( fixed #12 )
- Moved verification alert
- Show message if there are no search results
- `mode_view_page` no longer needs `data_string` ( fixed #5 )

### CODE REVIEW

File: static/search.js [hunk 1]
```diff
@@ -175,7 +200,7 @@ function addCard(result) {
             */
     card = document.createElement("div");
     card.setAttribute("role", "button");
-    card.setAttribute("onclick", `document.location.href = '/mod?name=${result.name}'`);
+    card.setAttribute("onclick", `document.location.href = '/mod?name=${result.name}&version==${result.version}'`);
```
Comment (vicky5124) [inline static/search.js]: Issue not fully fixed, this still needs verification.

**Review by vicky5124 — CHANGES_REQUESTED** [review]

**Review by vicky5124 — APPROVED** [review]
